import os
import glob
import numpy as np
import torch
from torch.utils.data import Dataset

class DynamicsDataset(Dataset):
    def __init__(self, dataset_dir, **kwargs):
        self.dataset_dir = dataset_dir
        # Find all .npz files generated by your sweep_runner.py
        self.files = glob.glob(os.path.join(dataset_dir, "**/*.npz"), recursive=True)
        
        # Statistics for normalization (Standardization)
        # In a real scenario, you'd pre-calculate these from the dataset
        self.std = torch.tensor([1.0, 1.0, 1.0]) 
        self.threshold = torch.tensor([0.5, 0.5, 0.5])

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        data = np.load(self.files[idx], allow_pickle=True)
        
        # Extract inputs (Parameters used in the simulation)
        # Convert the dictionary-like data back to tensors
        return {
            'scores': torch.from_numpy(data['score']).float(),      # Grasp success metric
            'input_ori': torch.tensor([data['angle']]).float(),     # Approach angle
            'input_pos': torch.tensor([data['tension'], data['base_rad']]).float(), # Physics params
            'ctrlpts': torch.from_numpy(data['rod_pos']).float(),   # Final rod shape
            'object_vertices': torch.zeros((1, 512, 3))            # Placeholder for cylinder
        }