import argparse

def parser():
    parser = argparse.ArgumentParser(description="Run Squirrel Finger Simulation.")
    parser.add_argument("--sol", type=str, default="approach_angle",
                        choices=["standard", "approach_angle", "nonuniform_tendon", "change_tendon_direction"])
    parser.add_argument("--approach_deg", type=float, default=45.0)
    parser.add_argument("--debug", action="store_true")
    parser.add_argument("--E", type=float, default=2e7)
    parser.add_argument("--tension", type=float, default=0.4)
    parser.add_argument("--damping", type=float, default=0.8)
    parser.add_argument("--n_elements", type=int, default=80)
    parser.add_argument("--cyl_rad", type=float, default=0.015)
    parser.add_argument("--k_contact", type=float, default=1.25e3)
    parser.add_argument("--base_len", type=float, default=0.10)
    parser.add_argument("--base_rad", type=float, default=0.005)
    parser.add_argument("--nu_contact", type=float, default=5.0)
    parser.add_argument("--mu_contact", type=float, default=0.6)
    parser.add_argument("--vel_damp_contact", type=int, default=10)
    parser.add_argument("--poisson_nu", type=float, default=0.4)
    parser.add_argument("--v_mass", type=float, default=0.002)
    parser.add_argument("--num_v", type=int, default=3)
    parser.add_argument("--v_start", type=int, default=30)
    parser.add_argument("--v_end", type=int, default=62)
    parser.add_argument("--v_height", type=float, default=0.005)
    parser.add_argument("--joint_softness", type=float, default=0.01)
    parser.add_argument("--v_mode", type=str, default="uniform", choices=["uniform", "manual"])
    parser.add_argument("--v_list", type=str, default="30,46,62")
    parser.add_argument("--body_mass", type=float, default=0.5)
    parser.add_argument("--suffix", type=str, default="default")
    parser.add_argument("--output_dir", type=str, default="squirrel_paw_results")
    return parser.parse_args()