#!/usr/bin/env python3
"""
Randomly sample MP4 simulation videos from a dataset folder and build one grid GIF.

Default behavior:
  - sample 32 MP4 files recursively
  - arrange them as 4 rows x 8 columns
  - save individual GIFs plus one combined GIF

Example:
  python TendonForces/sample_mp4_grid_gif.py \
      --dataset_dir "/full/path/to/TendonForces/runs/exp3" \
      --output_dir "/full/path/to/slide_gifs" \
      --seed 0

If your videos are under a verification folder:
  python TendonForces/sample_mp4_grid_gif.py \
      --dataset_dir "/full/path/to/generator/runs/sample_exp3/sim_verification_bending_only" \
      --output_dir "/full/path/to/slide_gifs"
"""

import argparse
import random
import re
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

from moviepy.editor import VideoFileClip, clips_array
from PIL import Image


# Pillow >= 10 removed Image.ANTIALIAS; MoviePy 1.0.3 still expects it.
if not hasattr(Image, "ANTIALIAS"):
    Image.ANTIALIAS = Image.Resampling.LANCZOS


VIDEO_EXTS = {".mp4"}

PARALLEL_RUNNER_PATTERN = re.compile(
    r"_T(?P<tension>[^_]+)"
    r"_BR(?P<base_rad>[^_]+)"
    r"_BL(?P<base_len>[^_]+)"
    r"_AR(?P<ankle_wrap_radius>[^_]+)"
    r"_AK(?P<ankle_stiffness>[^_]+)"
    r"_A(?P<approach_deg>[^_]+)"
    r"_JS(?P<joint_softness>[^_]+)"
    r"_JP(?P<v_list>[^_]+)_"
)


def find_videos(dataset_dir: str) -> List[Path]:
    root = Path(dataset_dir).expanduser().resolve()
    if not root.exists():
        raise FileNotFoundError(f"Dataset directory does not exist: {root}")
    if not root.is_dir():
        raise NotADirectoryError(f"Expected a directory, got: {root}")

    videos = [
        path
        for path in root.rglob("*")
        if path.is_file() and path.suffix.lower() in VIDEO_EXTS
    ]
    return sorted(videos)


def center_crop_clip(clip: VideoFileClip, crop_w: int, crop_h: int):
    """Center-crop a clip to crop_w x crop_h, clamped to the clip's size."""
    w, h = clip.size
    crop_w = min(int(crop_w), int(w))
    crop_h = min(int(crop_h), int(h))
    x1 = max(0, int((w - crop_w) / 2))
    y1 = max(0, int((h - crop_h) / 2))
    x2 = x1 + crop_w
    y2 = y1 + crop_h
    return clip.crop(x1=x1, y1=y1, x2=x2, y2=y2)


def pad_sequence(seq: Sequence, target_len: int):
    """Pad a sequence with blank clips later in the grid creation step."""
    return list(seq) + [None] * max(0, target_len - len(seq))


def choose_videos(videos: Sequence[Path], n: int, seed: int) -> List[Path]:
    if n <= 0:
        raise ValueError("--n must be positive")
    if len(videos) == 0:
        raise FileNotFoundError("No MP4 files found in the dataset directory.")

    rng = random.Random(seed)
    if len(videos) < n:
        print(
            f"[WARN] Requested n={n}, but only found {len(videos)} MP4 files. "
            f"Using all available videos."
        )
        chosen = list(videos)
        rng.shuffle(chosen)
        return chosen

    return rng.sample(list(videos), n)


def parse_softness_text(text: str) -> Tuple[float, ...]:
    return tuple(float(x) for x in text.split("-") if x.strip() != "")


def softness_hardness_score(text: str) -> float:
    values = parse_softness_text(text)
    if not values:
        return float("-inf")
    # In this simulator the joint multiplier scales stiffness. Larger values
    # are therefore harder/stiffer; smaller values are softer.
    return sum(values) / len(values)


def parse_parallel_runner_metadata(video_path: Path) -> Optional[Dict[str, str]]:
    """
    Parse names generated by TendonForces/parallel_runner_ray.py.

    Expected suffix inside MP4 name:
      T..._BR..._BL..._AR..._AK..._A..._JS..._JP..._<timestamp>

    Example:
      output_..._T3.0_BR0.01025_BL0.2_AR0.02_AK500.0_A45.0_
      JS0.003000-0.002000-0.001000_JP38-58-80_....mp4
    """
    match = PARALLEL_RUNNER_PATTERN.search(video_path.stem)
    if match is None:
        return None
    return match.groupdict()


def sweep_group_key(meta: Dict[str, str]) -> Tuple[str, ...]:
    """Group by all generation params except joint softness."""
    return (
        meta["tension"],
        meta["base_rad"],
        meta["base_len"],
        meta["ankle_wrap_radius"],
        meta["ankle_stiffness"],
        meta["approach_deg"],
        meta["v_list"],
    )


def tension_sweep_group_key(meta: Dict[str, str]) -> Tuple[str, ...]:
    """Group by all generation params except tendon tension/force."""
    return (
        meta["base_rad"],
        meta["base_len"],
        meta["ankle_wrap_radius"],
        meta["ankle_stiffness"],
        meta["approach_deg"],
        meta["joint_softness"],
        meta["v_list"],
    )


def choose_joint_softness_sweep(
    videos: Sequence[Path],
    seed: int,
    max_count: Optional[int] = None,
) -> Tuple[List[Path], Dict[str, str]]:
    """
    Select one matched sweep where all parsed params are identical except JS.

    If several valid groups exist, choose among the largest groups
    deterministically using --seed. Within the chosen group, sort from harder
    joints to softer joints.
    """
    grouped: Dict[Tuple[str, ...], Dict[str, Tuple[Path, Dict[str, str]]]] = {}
    skipped = 0

    for path in videos:
        meta = parse_parallel_runner_metadata(path)
        if meta is None:
            skipped += 1
            continue
        key = sweep_group_key(meta)
        js = meta["joint_softness"]
        grouped.setdefault(key, {})
        # If duplicate videos exist for the same group+softness, keep the first
        # sorted path for deterministic behavior.
        if js not in grouped[key] or str(path) < str(grouped[key][js][0]):
            grouped[key][js] = (path, meta)

    candidate_groups = [
        (key, by_softness)
        for key, by_softness in grouped.items()
        if len(by_softness) >= 2
    ]

    if not candidate_groups:
        raise ValueError(
            "Could not find an exact joint-softness sweep where all other "
            "parameters are identical and only JS changes. The filename parser "
            "worked, but every non-JS parameter group appears to have only one "
            "joint-softness value. This is expected for randomly generated "
            "datasets unless you explicitly generated controlled sweeps. "
            "Try --relaxed_sweep for a presentation montage with one example "
            "per JS profile. "
            f"Parsed groups: {len(grouped)}; skipped non-matching videos: {skipped}."
        )

    max_group_size = max(len(by_softness) for _, by_softness in candidate_groups)
    largest_groups = [
        (key, by_softness)
        for key, by_softness in candidate_groups
        if len(by_softness) == max_group_size
    ]

    rng = random.Random(seed)
    key, by_softness = rng.choice(largest_groups)

    sorted_items = sorted(
        by_softness.items(),
        key=lambda item: softness_hardness_score(item[0]),
        reverse=True,
    )
    if max_count is not None and max_count > 0:
        sorted_items = sorted_items[:max_count]

    selected = [path for _, (path, _) in sorted_items]
    representative_meta = sorted_items[0][1][1].copy()
    representative_meta["joint_softness_values_hard_to_soft"] = ", ".join(
        js for js, _ in sorted_items
    )
    representative_meta["group_size"] = str(len(sorted_items))
    representative_meta["num_candidate_groups"] = str(len(candidate_groups))
    representative_meta["num_skipped_nonmatching_videos"] = str(skipped)

    return selected, representative_meta


def choose_relaxed_joint_softness_sweep(
    videos: Sequence[Path],
    seed: int,
    max_count: Optional[int] = None,
) -> Tuple[List[Path], Dict[str, str]]:
    """
    Presentation-friendly fallback: choose one sample per JS profile.

    This does NOT keep all other parameters fixed. It is useful when the
    dataset was generated randomly and does not contain exact controlled
    sweeps. The output is still sorted hard -> soft.
    """
    by_softness: Dict[str, List[Tuple[Path, Dict[str, str]]]] = {}
    skipped = 0

    for path in videos:
        meta = parse_parallel_runner_metadata(path)
        if meta is None:
            skipped += 1
            continue
        by_softness.setdefault(meta["joint_softness"], []).append((path, meta))

    if len(by_softness) < 2:
        raise ValueError(
            "Could not build relaxed joint-softness sweep because fewer than "
            f"two JS profiles were found. Parsed JS profiles: {len(by_softness)}; "
            f"skipped non-matching videos: {skipped}."
        )

    rng = random.Random(seed)
    sorted_js = sorted(by_softness.keys(), key=softness_hardness_score, reverse=True)
    if max_count is not None and max_count > 0:
        sorted_js = sorted_js[:max_count]

    selected = []
    selected_meta = []
    for js in sorted_js:
        path, meta = rng.choice(by_softness[js])
        selected.append(path)
        selected_meta.append(meta)

    representative_meta = {
        "joint_softness_values_hard_to_soft": ", ".join(sorted_js),
        "group_size": str(len(selected)),
        "num_js_profiles": str(len(by_softness)),
        "num_skipped_nonmatching_videos": str(skipped),
        "relaxed_sweep": "true",
        "warning": "Other parameters are not held constant in relaxed_sweep mode.",
    }
    return selected, representative_meta


def choose_tendon_force_sweep(
    videos: Sequence[Path],
    seed: int,
    max_count: Optional[int] = None,
) -> Tuple[List[Path], Dict[str, str]]:
    """
    Select one matched sweep where all parsed params are identical except T.

    The selected row is sorted from low tendon force/tension to high tendon
    force/tension.
    """
    grouped: Dict[Tuple[str, ...], Dict[str, Tuple[Path, Dict[str, str]]]] = {}
    skipped = 0

    for path in videos:
        meta = parse_parallel_runner_metadata(path)
        if meta is None:
            skipped += 1
            continue
        key = tension_sweep_group_key(meta)
        tension = meta["tension"]
        grouped.setdefault(key, {})
        if tension not in grouped[key] or str(path) < str(grouped[key][tension][0]):
            grouped[key][tension] = (path, meta)

    candidate_groups = [
        (key, by_tension)
        for key, by_tension in grouped.items()
        if len(by_tension) >= 2
    ]

    if not candidate_groups:
        raise ValueError(
            "Could not find a tendon-force/tension sweep. This mode expects MP4 "
            "filenames generated by parallel_runner_ray.py with fields like "
            "T..._BR..._BL..._AR..._AK..._A..._JS..._JP.... "
            f"Parsed groups: {len(grouped)}; skipped non-matching videos: {skipped}."
        )

    max_group_size = max(len(by_tension) for _, by_tension in candidate_groups)
    largest_groups = [
        (key, by_tension)
        for key, by_tension in candidate_groups
        if len(by_tension) == max_group_size
    ]

    rng = random.Random(seed)
    key, by_tension = rng.choice(largest_groups)

    sorted_items = sorted(
        by_tension.items(),
        key=lambda item: float(item[0]),
    )
    if max_count is not None and max_count > 0:
        sorted_items = sorted_items[:max_count]

    selected = [path for _, (path, _) in sorted_items]
    representative_meta = sorted_items[0][1][1].copy()
    representative_meta["tension_values_low_to_high"] = ", ".join(
        tension for tension, _ in sorted_items
    )
    representative_meta["group_size"] = str(len(sorted_items))
    representative_meta["num_candidate_groups"] = str(len(candidate_groups))
    representative_meta["num_skipped_nonmatching_videos"] = str(skipped)

    return selected, representative_meta


def make_blank_clip(width: int, height: int, duration: float):
    """Create a black silent clip used when n is smaller than rows*cols."""
    from moviepy.editor import ColorClip

    return ColorClip(size=(width, height), color=(0, 0, 0), duration=duration)


def convert_one_to_gif(
    video_path: Path,
    output_path: Path,
    crop_w: int,
    crop_h: int,
    fps: int,
    max_duration: float,
) -> None:
    """Save one cropped MP4 as an individual GIF."""
    clip = VideoFileClip(str(video_path))
    try:
        duration = min(float(clip.duration), float(max_duration))
        clip = clip.subclip(0, duration)
        clip = center_crop_clip(clip, crop_w, crop_h)
        clip.write_gif(str(output_path), fps=fps, program="ffmpeg")
    finally:
        clip.close()


def load_grid_clips(
    videos: Sequence[Path],
    crop_w: int,
    crop_h: int,
    fps: int,
    max_duration: float,
) -> Tuple[List, float]:
    """Load and standardize clips for the combined grid GIF."""
    raw_clips = [VideoFileClip(str(path)) for path in videos]
    if not raw_clips:
        raise ValueError("No clips to load.")

    duration = min(min(float(c.duration) for c in raw_clips), float(max_duration))
    grid_clips = []

    for clip in raw_clips:
        c = clip.subclip(0, duration)
        c = center_crop_clip(c, crop_w, crop_h)
        c = c.resize((crop_w, crop_h))
        grid_clips.append(c)

    return grid_clips, duration


def close_clips(clips: Iterable) -> None:
    for clip in clips:
        if clip is not None:
            clip.close()


def write_selected_list(output_path: Path, selected: Sequence[Path]) -> None:
    with output_path.open("w") as f:
        for idx, path in enumerate(selected):
            f.write(f"{idx:03d}\t{path}\n")


def write_sweep_summary(output_path: Path, meta: Dict[str, str], selected: Sequence[Path]) -> None:
    with output_path.open("w") as f:
        f.write("Joint-softness sweep selected from parallel_runner_ray.py-style filenames\n")
        f.write("Sorted hard joints -> soft joints\n\n")
        for key in [
            "tension",
            "base_rad",
            "base_len",
            "ankle_wrap_radius",
            "ankle_stiffness",
            "approach_deg",
            "v_list",
            "joint_softness_values_hard_to_soft",
            "group_size",
            "num_candidate_groups",
            "num_skipped_nonmatching_videos",
        ]:
            if key in meta:
                f.write(f"{key}: {meta[key]}\n")
        f.write("\nselected videos:\n")
        for idx, path in enumerate(selected):
            parsed = parse_parallel_runner_metadata(path)
            js = "unknown" if parsed is None else parsed["joint_softness"]
            f.write(f"{idx:03d}\tJS={js}\t{path}\n")


def write_tension_sweep_summary(output_path: Path, meta: Dict[str, str], selected: Sequence[Path]) -> None:
    with output_path.open("w") as f:
        f.write("Tendon-force/tension sweep selected from parallel_runner_ray.py-style filenames\n")
        f.write("Sorted low tension -> high tension\n\n")
        for key in [
            "base_rad",
            "base_len",
            "ankle_wrap_radius",
            "ankle_stiffness",
            "approach_deg",
            "joint_softness",
            "v_list",
            "tension_values_low_to_high",
            "group_size",
            "num_candidate_groups",
            "num_skipped_nonmatching_videos",
        ]:
            if key in meta:
                f.write(f"{key}: {meta[key]}\n")
        f.write("\nselected videos:\n")
        for idx, path in enumerate(selected):
            parsed = parse_parallel_runner_metadata(path)
            tension = "unknown" if parsed is None else parsed["tension"]
            f.write(f"{idx:03d}\tT={tension}\t{path}\n")


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Randomly sample MP4 files from a dataset directory, convert each to GIF, "
            "and concatenate them into a single grid GIF for slides."
        )
    )
    parser.add_argument(
        "--dataset_dir",
        type=str,
        required=True,
        help="Full path to dataset/output directory containing MP4 files. Searched recursively.",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default=None,
        help="Where to save GIFs. Defaults to <dataset_dir>/sampled_gif_grid.",
    )
    parser.add_argument("--n", type=int, default=32, help="Number of videos to sample.")
    parser.add_argument("--cols", type=int, default=8, help="Number of GIFs per row.")
    parser.add_argument("--rows", type=int, default=4, help="Number of rows in the final grid.")
    parser.add_argument(
        "--jsoftness_sweep",
        action="store_true",
        help=(
            "Select one matched sweep from parallel_runner_ray.py-style filenames "
            "where all params are the same except joint_softness. The final GIF "
            "is one row sorted from harder joints to softer joints."
        ),
    )
    parser.add_argument(
        "--tendon_force_sweep",
        action="store_true",
        help=(
            "Select one matched sweep from parallel_runner_ray.py-style filenames "
            "where all params are the same except tendon tension/force T. The "
            "final GIF is one row sorted from low tension to high tension."
        ),
    )
    parser.add_argument(
        "--relaxed_sweep",
        action="store_true",
        help=(
            "If an exact sweep is not present, build a presentation-friendly "
            "row by sampling one video from each varied value. For JS sweeps, "
            "this means one example per joint-softness profile. Other params "
            "are not guaranteed to match."
        ),
    )
    parser.add_argument("--seed", type=int, default=0, help="Random seed for repeatable sampling.")
    parser.add_argument("--fps", type=int, default=8, help="GIF frames per second.")
    parser.add_argument(
        "--max_duration",
        type=float,
        default=5.0,
        help="Maximum seconds to keep from each video.",
    )
    parser.add_argument("--crop_w", type=int, default=320, help="Per-video crop/output width.")
    parser.add_argument("--crop_h", type=int, default=240, help="Per-video crop/output height.")
    parser.add_argument(
        "--grid_name",
        type=str,
        default="sampled_grid.gif",
        help="Filename for the combined grid GIF.",
    )
    parser.add_argument(
        "--skip_individual_gifs",
        action="store_true",
        help="Only write the combined grid GIF, not the individual GIF files.",
    )
    args = parser.parse_args()

    dataset_dir = Path(args.dataset_dir).expanduser().resolve()
    output_dir = (
        Path(args.output_dir).expanduser().resolve()
        if args.output_dir is not None
        else dataset_dir / "sampled_gif_grid"
    )
    individual_dir = output_dir / "individual_gifs"
    output_dir.mkdir(parents=True, exist_ok=True)
    individual_dir.mkdir(parents=True, exist_ok=True)

    target_grid_count = args.rows * args.cols
    if args.n != target_grid_count:
        print(
            f"[INFO] n={args.n}, but rows*cols={target_grid_count}. "
            f"The grid will contain {target_grid_count} cells; empty cells are black if needed."
        )

    videos = find_videos(str(dataset_dir))
    if args.jsoftness_sweep and args.tendon_force_sweep:
        raise ValueError("Choose only one sweep mode: --jsoftness_sweep or --tendon_force_sweep")

    if args.jsoftness_sweep:
        try:
            selected, sweep_meta = choose_joint_softness_sweep(
                videos=videos,
                seed=args.seed,
                max_count=args.n,
            )
        except ValueError:
            if not args.relaxed_sweep:
                raise
            print("[WARN] Exact joint-softness sweep not found; using --relaxed_sweep fallback.")
            selected, sweep_meta = choose_relaxed_joint_softness_sweep(
                videos=videos,
                seed=args.seed,
                max_count=args.n,
            )
        args.rows = 1
        args.cols = len(selected)
        args.grid_name = (
            args.grid_name
            if args.grid_name != "sampled_grid.gif"
            else "joint_softness_sweep.gif"
        )
        target_grid_count = args.rows * args.cols
        write_sweep_summary(output_dir / "joint_softness_sweep_summary.txt", sweep_meta, selected)
        print("[JSWEEP] selected matched group:")
        if sweep_meta.get("relaxed_sweep") == "true":
            print("  relaxed_sweep=true; other parameters are not held constant")
        else:
            print(
                "  "
                + ", ".join(
                    [
                        f"T={sweep_meta['tension']}",
                        f"BR={sweep_meta['base_rad']}",
                        f"BL={sweep_meta['base_len']}",
                        f"AR={sweep_meta['ankle_wrap_radius']}",
                        f"AK={sweep_meta['ankle_stiffness']}",
                        f"A={sweep_meta['approach_deg']}",
                        f"JP={sweep_meta['v_list']}",
                    ]
                )
            )
        print(f"[JSWEEP] hard -> soft JS: {sweep_meta['joint_softness_values_hard_to_soft']}")
    elif args.tendon_force_sweep:
        selected, sweep_meta = choose_tendon_force_sweep(
            videos=videos,
            seed=args.seed,
            max_count=args.n,
        )
        args.rows = 1
        args.cols = len(selected)
        args.grid_name = (
            args.grid_name
            if args.grid_name != "sampled_grid.gif"
            else "tendon_force_sweep.gif"
        )
        target_grid_count = args.rows * args.cols
        write_tension_sweep_summary(output_dir / "tendon_force_sweep_summary.txt", sweep_meta, selected)
        print("[TSWEEP] selected matched group:")
        print(
            "  "
            + ", ".join(
                [
                    f"BR={sweep_meta['base_rad']}",
                    f"BL={sweep_meta['base_len']}",
                    f"AR={sweep_meta['ankle_wrap_radius']}",
                    f"AK={sweep_meta['ankle_stiffness']}",
                    f"A={sweep_meta['approach_deg']}",
                    f"JS={sweep_meta['joint_softness']}",
                    f"JP={sweep_meta['v_list']}",
                ]
            )
        )
        print(f"[TSWEEP] low -> high tension: {sweep_meta['tension_values_low_to_high']}")
    else:
        selected = choose_videos(videos, args.n, args.seed)

    selected_list_path = output_dir / "selected_videos.txt"
    write_selected_list(selected_list_path, selected)

    print(f"[FOUND] {len(videos)} MP4 files")
    print(f"[SELECTED] {len(selected)} videos")
    print(f"[SAVED] selected list: {selected_list_path}")

    if not args.skip_individual_gifs:
        for idx, video_path in enumerate(selected):
            gif_path = individual_dir / f"{idx:03d}_{video_path.stem}.gif"
            print(f"[GIF {idx + 1}/{len(selected)}] {video_path.name} -> {gif_path.name}")
            convert_one_to_gif(
                video_path=video_path,
                output_path=gif_path,
                crop_w=args.crop_w,
                crop_h=args.crop_h,
                fps=args.fps,
                max_duration=args.max_duration,
            )

    grid_clips = []
    blanks = []
    grid = None
    try:
        grid_source_videos = selected[:target_grid_count]
        grid_clips, duration = load_grid_clips(
            videos=grid_source_videos,
            crop_w=args.crop_w,
            crop_h=args.crop_h,
            fps=args.fps,
            max_duration=args.max_duration,
        )

        padded = pad_sequence(grid_clips, target_grid_count)
        for idx, clip in enumerate(padded):
            if clip is None:
                blank = make_blank_clip(args.crop_w, args.crop_h, duration)
                blanks.append(blank)
                padded[idx] = blank

        clip_rows = [
            padded[row_idx * args.cols : (row_idx + 1) * args.cols]
            for row_idx in range(args.rows)
        ]
        grid = clips_array(clip_rows)

        grid_path = output_dir / args.grid_name
        print(f"[GRID] writing {args.rows}x{args.cols} GIF: {grid_path}")
        grid.write_gif(str(grid_path), fps=args.fps, program="ffmpeg")
        print(f"[DONE] Combined GIF saved to: {grid_path}")
    finally:
        if grid is not None:
            grid.close()
        close_clips(grid_clips)
        close_clips(blanks)


if __name__ == "__main__":
    main()
